import { task } from "@trigger.dev/sdk";
import { GoogleGenerativeAI } from "@google/generative-ai";

interface VideoSummaryInput {
  videoUrl: string;
}

export const videoSummaryTask = task({
  id: "video-summary",
  run: async (payload: VideoSummaryInput) => {
    const { videoUrl } = payload;

    // Validate environment variables
    const youtubeApiKey = process.env.YOUTUBE_API_KEY;
    const geminiApiKey = process.env.GEMINI_API_KEY;

    if (!youtubeApiKey) throw new Error("YOUTUBE_API_KEY is not set");
    if (!geminiApiKey) throw new Error("GEMINI_API_KEY is not set");

    // Initialize Gemini client
    const genAI = new GoogleGenerativeAI(geminiApiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-pro" });

    // Extract video ID from YouTube URL
    const videoId = extractVideoId(videoUrl);
    if (!videoId) throw new Error("Invalid YouTube URL");

    console.log(`Processing video: ${videoId}`);

    // Step 1: Get video metadata
    const videoData = await getVideoMetadata(videoId, youtubeApiKey);
    const { title, description } = videoData;

    console.log(`Video title: ${title}`);

    // Step 2: Summarize using Gemini
    const summary = await summarizeVideo(model, title, description);

    // Step 3: Generate markdown output
    const markdown = generateMarkdown(title, summary);

    console.log("\n=== VIDEO SUMMARY ===\n");
    console.log(markdown);

    return {
      videoId,
      videoTitle: title,
      summary,
      markdown,
    };
  },
});

function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }

  return null;
}

async function getVideoMetadata(
  videoId: string,
  apiKey: string
): Promise<{ title: string; description: string }> {
  const url = `https://www.googleapis.com/youtube/v3/videos?id=${videoId}&key=${apiKey}&part=snippet`;

  try {
    const response = await fetch(url);
    const data = (await response.json()) as any;
    const items = data.items;

    if (!items || items.length === 0) {
      throw new Error("Video not found");
    }

    const snippet = items[0].snippet;
    return {
      title: snippet.title,
      description: snippet.description,
    };
  } catch (error) {
    console.error("Error fetching video metadata:", error);
    throw new Error("Failed to fetch video metadata");
  }
}

async function summarizeVideo(
  model: any,
  title: string,
  description: string
): Promise<string> {
  try {
    const prompt = `Based on this YouTube video information, create a comprehensive summary in a nested bulleted list format.

Video Title: ${title}

Video Description: ${description}

Please create a summary that:
1. Lists the main topics covered in the video
2. Includes key points under each topic
3. Uses nested bullets for sub-points
4. Keeps each point to 1-2 sentences maximum
5. Is formatted as clean markdown

Generate the summary now:`;

    const response = await model.generateContent(prompt);
    return response.response.text();
  } catch (error) {
    console.error("Error summarizing video:", error);
    throw new Error("Failed to summarize video");
  }
}

function generateMarkdown(title: string, summary: string): string {
  let markdown = `# ${title}\n\n`;
  markdown += `## Summary\n\n${summary}\n\n`;
  markdown += `---\n*Generated by Video Summary Automation*\n`;
  return markdown;
}
